import React from 'react';

interface CodeEditorProps {
  code: string;
  onChange: (code: string) => void;
}

const CodeEditor: React.FC<CodeEditorProps> = ({ code, onChange }) => {
  
  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
      if (e.key === 'Tab') {
          e.preventDefault();
          const target = e.target as HTMLTextAreaElement;
          const start = target.selectionStart;
          const end = target.selectionEnd;
          const value = target.value;
          
          const newValue = value.substring(0, start) + '  ' + value.substring(end);
          onChange(newValue);
          
          // Need to set selection timeout to run after render
          setTimeout(() => {
              target.selectionStart = target.selectionEnd = start + 2;
          }, 0);
      }
  };

  return (
    <div className="flex flex-col h-full bg-game-dark">
      <div className="flex items-center justify-between px-4 py-2 bg-game-panel border-b border-game-border">
        <div className="flex space-x-4">
            <div className="text-sm text-accent-500 font-mono border-b-2 border-accent-500 px-2">GameScript.ts</div>
            <div className="text-sm text-gray-500 font-mono hover:text-gray-300 cursor-pointer px-2">PlayerController.ts</div>
            <div className="text-sm text-gray-500 font-mono hover:text-gray-300 cursor-pointer px-2">LevelManager.ts</div>
        </div>
        <div className="flex items-center space-x-2 text-xs text-gray-400">
            <span>TypeScript</span>
            <div className="w-2 h-2 rounded-full bg-blue-500"></div>
        </div>
      </div>
      
      <div className="relative flex-1 overflow-hidden">
        {/* Line Numbers - Simulated */}
        <div className="absolute left-0 top-0 bottom-0 w-10 bg-game-dark border-r border-game-border text-right pr-2 pt-4 text-gray-600 font-mono text-sm select-none pointer-events-none z-10">
            {code.split('\n').map((_, i) => (
                <div key={i} className="leading-6">{i + 1}</div>
            ))}
        </div>
        
        <textarea
            value={code}
            onChange={(e) => onChange(e.target.value)}
            onKeyDown={handleKeyDown}
            spellCheck={false}
            className="absolute inset-0 w-full h-full pl-12 pr-4 pt-4 bg-[#1e1e1e] text-gray-300 font-mono text-sm leading-6 resize-none focus:outline-none"
            style={{
                tabSize: 2,
                whiteSpace: 'pre',
                wordWrap: 'normal',
                overflow: 'auto'
            }}
        />
      </div>
      
      {/* Status Bar */}
      <div className="h-6 bg-accent-600 text-white text-[10px] flex items-center px-2">
         <span className="mr-4">Ln {code.split('\n').length}, Col 1</span>
         <span className="mr-4">UTF-8</span>
         <span>Generated by Gemini 3 Pro</span>
      </div>
    </div>
  );
};

export default CodeEditor;